apiVersion: v1
kind: Service
metadata:
  name: test-service-node
  labels:
    app: test-service-node
spec:
  type: LoadBalancer
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app: test-node
